### GET endpoint
GET http://localhost:8080/cu-manager


### Query email GET test

GET http://localhost:8080/cu-manager?email=Cesar.Waelchi13@gmail.com



### Post Test
POST http://localhost:8080/cu-manager
Content-Type: application/json

  { 
    "first_name": "Julie",
    "last_name": "Vu",
    "email": "JulieV@gmail.com",
    "parent_first_name": "Jonathan",
    "parent_last_name": "Vu",
    "address": {
        "street_address": "1523 Main Drive",
        "state": "NC",
        "zipcode": "31154",
        "country": "United States"
        },
    "student_lesson_time": {
      "weekday": "Friday",
      "startTime": "Fri Apr 28 2017 22:50:25 GMT-0400 (Eastern Daylight Time)",
      "endTime": "Fri Apr 28 2017 23:50:25 GMT-0400 (Eastern Daylight Time)"
    },
    "teacher_comments": "Student has made excellent progress.",
    "student_curriculum": [
        {
            "project_name": "A new musical creation",
            "project_description": "This piece is going to be amazing.",
            "teacher_project_comments": "Work on your phrasing.",
            "project_date": "Thu Apr 17 2016 13:45:55 GMT-0400 (Eastern Daylight Time)"
        },
        {
            "project_name": "asdflkn",
            "project_description": "This piece is going to be amazing.",
            "teacher_project_comments": "Work on your phrasing.",
            "project_date": "Thu Apr 17 2016 13:45:55 GMT-0400 (Eastern Daylight Time)"
        }
    ]
  }






### PUT Test with address

PUT http://localhost:8080/cu-manager/59052ceaad296b4974ed4a99
Content-Type: application/json

  {
    "id": "59052ceaad296b4974ed4a99",
    "address": {
        "street_address": "Some other address",
        "state": "CA",
        "zipcode": "85154"  }
  }




### PUT Test with parent_first_name

PUT http://localhost:8080/cu-manager/590508f3879a2a4070f1aea4
Content-Type: application/json

  {
    "id": "590508f3879a2a4070f1aea4",
    "parent_first_name": "Jane"
  }



### PUT Test with parent_first_name

PUT http://localhost:8080/cu-manager/59052ceaad296b4974ed4aa1
Content-Type: application/json

  {
    "index": "0",
    "id": "59052ceaad296b4974ed4aa1",
      "student_curriculum":
        {
          "project_name": "some other thing",
          "project_description": "Testing this.",
          "teacher_project_comments": "New comments.",
          "project_date": "2017-04-29T22:40:20.455Z"
        }    
  }

# 5905165542c15b3040ece238
### 

# db['student-teacher-dbs'].updateOne (
# {"_id" : ObjectId("59052ceaad296b4974ed4a85") }, 
# { $set: { "student_curriculum.0": 
# {
#   "project_name": "some other thing",
#   "project_description": "Testing this.",
#   "teacher_project_comments": "New comments.",
#   "_id": ObjectId("5905165542c15b3040ece23e"),
#   "project_date": "2017-04-29T22:40:20.455Z"
#   }}}, 
#   {new:true} )
